PKGDIR		?= ../../..
L4DIR		?= $(PKGDIR)/../..

TARGET		= libsupc++-support
SRC_C		= memset.c 
SRC_CC		= abort.cc

include $(PKGDIR)/lib/Makefile.inc
include $(L4DIR)/mk/lib.mk

$(GENERAL_D_LOC): $(L4DIR)/pkg/cxx/lib/Makefile.inc
