#! /bin/sh

set -x

TMPDIR=$(mktemp -d)

exithandler()
{
  rm -r $TMPDIR
}

trap exithandler EXIT

cd ..

for i in mk/defconfig/config.*; do
  cp $i $TMPDIR/.kconfig
  make O=$TMPDIR oldconfig
  diff -u $i $TMPDIR/.kconfig
  grep -v '^CONFIG_DROPS_' $TMPDIR/.kconfig > $i
  rm $TMPDIR/.kconfig $TMPDIR/.config.all $TMPDIR/.config
done
